export const TODAY = "2026-06-04";

export const people = [
  { id: "admin", name: "관리자", role: "관리자", permissionRole: "admin", color: "#475569", emoji: "🛡️", isTeamMember: false },
  { id: "lead", name: "박도윤", role: "팀장", permissionRole: "lead", color: "#2563eb", emoji: "🦉", isTeamMember: true },
  { id: "seoyeon", name: "김서연", role: "책임", permissionRole: "member", color: "#0f766e", emoji: "🌿", isTeamMember: true },
  { id: "junho", name: "이준호", role: "책임", permissionRole: "member", color: "#7c3aed", emoji: "🐳", isTeamMember: true },
  { id: "minji", name: "최민지", role: "선임", permissionRole: "member", color: "#c2410c", emoji: "🦊", isTeamMember: true },
  { id: "haram", name: "정하람", role: "선임", permissionRole: "member", color: "#0369a1", emoji: "🌱", isTeamMember: true },
  { id: "taeseok", name: "윤태석", role: "매니저", permissionRole: "member", color: "#4d7c0f", emoji: "🐢", isTeamMember: true },
  { id: "jieun", name: "오지은", role: "매니저", permissionRole: "member", color: "#be185d", emoji: "🍀", isTeamMember: true }
];

export const statuses = ["계획", "진행중", "검토/대기", "완료", "보류"];
export const categories = ["전체", "기획보고", "월간보고", "자료조사", "전략과제", "임원보고", "운영"];
export const tagOptions = ["탄소중립", "AI활용", "시장동향", "투자검토", "회의체", "외부자료", "KPI", "정책"];
export const assignerTypes = ["원장님", "소장님", "그룹장님", "팀장님", "개인", "기타"];

export const initialCalendarEvents = [
  {
    id: "e-001",
    title: "전략과제 중간 공유회",
    date: "2026-06-11",
    startDate: "2026-06-11",
    endDate: "2026-06-13",
    scope: "team",
    ownerId: "lead",
    note: "3일 동안 진행되는 팀 공유 일정 샘플"
  },
  {
    id: "e-002",
    title: "김서연 외부 자문 미팅",
    date: "2026-06-16",
    startDate: "2026-06-16",
    endDate: "2026-06-16",
    scope: "personal",
    ownerId: "seoyeon",
    note: "기획보고 근거 확인"
  },
  {
    id: "e-003",
    title: "월간보고 자료 마감 공지",
    date: "2026-06-24",
    startDate: "2026-06-24",
    endDate: "2026-06-24",
    scope: "team",
    ownerId: "junho",
    note: "공용 캘린더 공지"
  }
];

export const initialTasks = [
  {
    id: "t-001",
    title: "상반기 전략과제 기획보고 초안",
    description: "연구기획그룹 전략과제의 상반기 추진 논리와 주요 실행안을 정리합니다.",
    ownerId: "seoyeon",
    assignerId: "lead",
    assignerType: "팀장님",
    creatorId: "lead",
    status: "진행중",
    priority: "높음",
    category: "기획보고",
    tags: ["전략과제", "임원보고"],
    startDate: "2026-06-03",
    dueDate: "2026-06-10",
    progress: 46,
    subtasks: [
      { id: "st-001-1", title: "보고서 목차 정리", done: true },
      { id: "st-001-2", title: "핵심 메시지 초안 작성", done: true },
      { id: "st-001-3", title: "수치 근거 링크 보강", done: false },
      { id: "st-001-4", title: "팀장 검토 요청", done: false }
    ],
    archived: false,
    isNewAssignment: true,
    recurring: null,
    links: [
      { title: "전략과제 전년도 보고서", url: "https://intra.research-strategy.local/reports/strategy-2025", type: "보고서" },
      { title: "시장 동향 데이터", url: "https://intra.research-strategy.local/data/market-trends", type: "자료" }
    ],
    updates: [
      { authorId: "seoyeon", date: "2026-06-04", text: "목차와 핵심 메시지 1차 정리 완료. 오후에 수치 근거 보강 예정." },
      { authorId: "lead", date: "2026-06-03", text: "실행과제별 기대효과가 먼저 보이도록 구성해 주세요." }
    ]
  },
  {
    id: "t-002",
    title: "6월 월간보고 운영자료 취합",
    description: "팀별 진행률, 지연 이슈, 다음 달 계획을 월간보고 양식으로 취합합니다.",
    ownerId: "junho",
    assignerId: "lead",
    assignerType: "팀장님",
    creatorId: "lead",
    status: "진행중",
    priority: "보통",
    category: "월간보고",
    tags: ["KPI", "회의체"],
    startDate: "2026-06-01",
    dueDate: "2026-06-04",
    progress: 72,
    subtasks: [
      { id: "st-002-1", title: "팀별 제출 현황 확인", done: true },
      { id: "st-002-2", title: "지연 이슈 요약", done: true },
      { id: "st-002-3", title: "최종 취합본 공유", done: false }
    ],
    archived: false,
    isNewAssignment: false,
    recurring: "매월",
    recurringDetail: "매월 첫째 주 월-목",
    recurringInterval: 1,
    recurringWeekdays: [1],
    recurringStartDate: "2026-06-01",
    recurringEndDate: "",
    recurringNoEnd: true,
    recurringDurationDays: 4,
    links: [{ title: "월간보고 폴더", url: "https://intra.research-strategy.local/drive/monthly-report", type: "드라이브" }],
    updates: [{ authorId: "junho", date: "2026-06-04", text: "미제출 항목 2건 확인. 담당자에게 리마인드 완료." }]
  },
  {
    id: "t-003",
    title: "AI 기반 연구기획 업무 활용사례 조사",
    description: "국내외 연구기획 업무의 AI 도입 사례와 적용 가능 업무를 정리합니다.",
    ownerId: "minji",
    assignerId: "lead",
    assignerType: "팀장님",
    creatorId: "lead",
    status: "계획",
    priority: "보통",
    category: "자료조사",
    tags: ["AI활용", "외부자료"],
    startDate: "2026-06-04",
    dueDate: "2026-06-18",
    progress: 8,
    archived: false,
    isNewAssignment: true,
    recurring: null,
    links: [{ title: "조사 템플릿", url: "https://intra.research-strategy.local/templates/research-case", type: "양식" }],
    updates: []
  },
  {
    id: "t-004",
    title: "탄소중립 기술 포트폴리오 업데이트",
    description: "주요 기술군의 투자 우선순위와 리스크를 최신 자료 기준으로 갱신합니다.",
    ownerId: "haram",
    assignerId: "lead",
    assignerType: "팀장님",
    creatorId: "lead",
    status: "검토/대기",
    priority: "높음",
    category: "전략과제",
    tags: ["탄소중립", "투자검토"],
    startDate: "2026-05-27",
    dueDate: "2026-06-03",
    progress: 88,
    archived: false,
    isNewAssignment: false,
    recurring: null,
    links: [{ title: "기술 포트폴리오 시트", url: "https://intra.research-strategy.local/sheets/tech-portfolio", type: "시트" }],
    updates: [{ authorId: "haram", date: "2026-06-03", text: "검토본 업로드. 투자 우선순위 의견 대기 중." }]
  },
  {
    id: "t-005",
    title: "임원보고 Q&A 예상질문 정리",
    description: "주요 보고 안건별 예상질문과 답변 방향을 짧게 정리합니다.",
    ownerId: "taeseok",
    assignerId: "lead",
    assignerType: "팀장님",
    creatorId: "lead",
    status: "계획",
    priority: "높음",
    category: "임원보고",
    tags: ["임원보고", "회의체"],
    startDate: "2026-06-06",
    dueDate: "2026-06-12",
    progress: 0,
    archived: false,
    isNewAssignment: false,
    recurring: null,
    links: [],
    updates: []
  },
  {
    id: "t-006",
    title: "정책 변화 모니터링 메모",
    description: "신규 정부 정책과 연구지원 제도 변화를 요약해 팀 공유용 메모로 만듭니다.",
    ownerId: "jieun",
    assignerId: "lead",
    assignerType: "팀장님",
    creatorId: "jieun",
    status: "진행중",
    priority: "낮음",
    category: "자료조사",
    tags: ["정책", "외부자료"],
    startDate: "2026-05-30",
    dueDate: "2026-06-07",
    progress: 55,
    archived: false,
    isNewAssignment: false,
    recurring: "매월",
    recurringDetail: "매월 첫째 주 정책자료 확인",
    recurringInterval: 1,
    recurringWeekdays: [1],
    recurringStartDate: "2026-05-30",
    recurringEndDate: "",
    recurringNoEnd: true,
    recurringDurationDays: 3,
    links: [{ title: "정책 모니터링 링크", url: "https://intra.research-strategy.local/library/policy-monitoring", type: "웹" }],
    updates: [{ authorId: "jieun", date: "2026-06-04", text: "산업부 발표자료 3건 추가 확인." }]
  },
  {
    id: "t-007",
    title: "팀장 주간 업무 배정 정리",
    description: "이번 주 팀 업무 배정 현황과 병목 업무를 공개 패널에 정리합니다.",
    ownerId: "lead",
    assignerId: "lead",
    assignerType: "팀장님",
    creatorId: "lead",
    status: "진행중",
    priority: "보통",
    category: "운영",
    tags: ["회의체", "KPI"],
    startDate: "2026-06-04",
    dueDate: "2026-06-05",
    progress: 64,
    archived: false,
    isNewAssignment: false,
    recurring: "매주",
    recurringDetail: "5주마다 화요일, 목요일",
    recurringInterval: 5,
    recurringWeekdays: [2, 4],
    recurringStartDate: "2026-06-05",
    recurringEndDate: "2026-10-31",
    recurringNoEnd: false,
    recurringDurationDays: 2,
    links: [],
    updates: [{ authorId: "lead", date: "2026-06-04", text: "지연 업무 1건은 오늘 검토회의에서 우선 조정 예정." }]
  },
  {
    id: "t-008",
    title: "기획보고 데이터 근거 검증",
    description: "보고서에 들어갈 수치와 출처를 확인하고 자료 링크를 보강합니다.",
    ownerId: "seoyeon",
    assignerId: "lead",
    assignerType: "팀장님",
    creatorId: "seoyeon",
    status: "보류",
    priority: "보통",
    category: "기획보고",
    tags: ["외부자료", "KPI"],
    startDate: "2026-05-28",
    dueDate: "2026-06-02",
    progress: 34,
    archived: false,
    isNewAssignment: false,
    recurring: null,
    links: [{ title: "검증 체크리스트", url: "https://intra.research-strategy.local/docs/evidence-checklist", type: "문서" }],
    updates: [{ authorId: "seoyeon", date: "2026-06-02", text: "외부 통계 출처 1건 확인 필요. 보류 처리." }]
  },
  {
    id: "t-009",
    title: "지난 달 완료 업무 회고",
    description: "완료 업무의 관련 링크와 재사용 가능한 템플릿을 정리합니다.",
    ownerId: "minji",
    assignerId: "lead",
    assignerType: "팀장님",
    creatorId: "minji",
    status: "완료",
    priority: "낮음",
    category: "운영",
    tags: ["KPI"],
    startDate: "2026-05-20",
    dueDate: "2026-05-31",
    completedAt: "2026-05-31",
    completedBy: "minji",
    progress: 100,
    archived: false,
    isNewAssignment: false,
    recurring: "매월",
    recurringDetail: "매월 마지막 주",
    recurringInterval: 1,
    recurringWeekdays: [5],
    recurringStartDate: "2026-05-20",
    recurringEndDate: "",
    recurringNoEnd: true,
    recurringDurationDays: 2,
    links: [{ title: "회고 메모", url: "https://intra.research-strategy.local/docs/monthly-retro", type: "문서" }],
    updates: [{ authorId: "minji", date: "2026-05-31", text: "재사용 템플릿 3종 정리 완료." }],
    statusHistory: [{ from: "진행중", to: "완료", actorId: "minji", date: "2026-05-31", note: "완료 처리" }]
  },
  {
    id: "t-010",
    title: "5월 정책자료 링크 정리",
    description: "지난달 정책 모니터링 링크와 요약 메모를 보관용 자료로 정리했습니다.",
    ownerId: "jieun",
    assignerId: "jieun",
    assignerType: "개인",
    creatorId: "jieun",
    status: "완료",
    priority: "낮음",
    category: "자료조사",
    tags: ["정책", "외부자료"],
    startDate: "2026-05-01",
    dueDate: "2026-05-30",
    completedAt: "2026-06-01",
    completedBy: "jieun",
    progress: 100,
    archived: true,
    isNewAssignment: false,
    recurring: "매월",
    recurringDetail: "매월 말 보관 정리",
    recurringInterval: 1,
    recurringWeekdays: [5],
    recurringStartDate: "2026-05-01",
    recurringEndDate: "",
    recurringNoEnd: true,
    recurringDurationDays: 2,
    links: [{ title: "5월 정책자료 모음", url: "https://intra.research-strategy.local/drive/policy-2026-05", type: "드라이브" }],
    updates: [{ authorId: "jieun", date: "2026-06-01", text: "완료 자료를 보관 처리. 필요 시 보관함에서 재확인 가능." }],
    statusHistory: [{ from: "진행중", to: "완료", actorId: "jieun", date: "2026-06-01", note: "완료 처리" }]
  }
];
